### ISSUE TITLE
Support chunking large model's protobuf blob into 512MB blocks on AI.MODELSET 

### ISSUE THREAD

**Issue by filipecosta90** [RedisAI/JRedisAI#19]
Since Redis supports strings up to 512MB, blobs for very large models need to be chunked. 
Further reference here: https://oss.redislabs.com/redisai/commands/#aimodelset

**Comment by sazzad16** [comment]
@filipecosta90 @gkorland 

There is a Blob class in Java but that's very much specific to JDBC api. Using JDBC api just for using Blob is not very logical.

From https://stackoverflow.com/questions/1132161/which-type-do-i-use-to-represent-an-arbitrary-blob-in-java, we can know about 3 options, `byte[]`, `ByteBuffer` and `(ByteArray)InputStream`.

ByteBuffer is generally used NIO which Jedis doesn't use. So we are somehow left with two other options.

At https://github.com/RedisAI/JRedisAI/blob/master/src/main/java/com/redislabs/redisai/Model.java, we can see that blob is represented as `byte[]`. And whatever the datatype is, Jedis processes the data in socket chunked by `8KB` size during both read and write operations. These chunking codes are almost the copy of ByteArrayInputStream.

Does this answer your requirement about blob representation and chunking?
